[package]
name = "generation"
version = "0.1.0"
edition = "2021"
autobins = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "3.0.4", features = ["full", "extra-traits"] }
quote = "1.0.23"
proc-macro2 = "1.0"
rust-format = { version = "0.3.4", features = ["token_stream"] }
convert_case = "0.12.0"
diesel = { version = "2", features = ["sqlite", "32-column-tables"] }
log = "0.4.34"

[[bin]]
name = "populate"
path = "src/bin/populate.rs"
libsqlite3-sys = { version = "0.30", features = ["bundled"] }